version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      - "3333:3333"
      - "5555:5555"
      - "7777:7777"
      - "8888:8888"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge